services:
  # redis service used as a persistent storage
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  ### Telephony servers ###
  twilio-app:
    image: twilio-app:latest
    build:
      context: ..
      dockerfile: local_setup/dockerfiles/twilio_server.Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    env_file:
      - .env